[tool.bandit]
exclude_dirs = ["tests", "features"]

[tool.black]
max-line-length = 99
target-version = ['py310', 'py311']

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.mypy]
ignore_missing_imports = true
# https://stackoverflow.com/questions/62265366/does-mypy-only-type-check-a-function-if-it-declares-a-return-type
check_untyped_defs = true


[tool.poetry]
name = "cakemold"
version = "0.0.1"
description = "Cake Mold is a template to build python projects"
authors = ["Lu√≠s Miranda <luistm@gmail.com>"]
license = "The Unlicence"
readme = "README.md"
packages = [{include = "cakemold", from = "src"}]

[tool.poetry.dependencies]
python = "3.10.10"

[tool.poetry.group.dev.dependencies]
bandit = {extras = ["toml"], version = "^1.7.5"}
behave = "^1.2.6"
black = "^23.3.0"
coverage = "^7.2.5"
flake8 = "^6.0.0"
isort = "^5.12.0"
mypy = "^1.3.0"
nox = "^2023.4.22"
pre-commit = "^3.3.2"
pytest = "^7.3.1"
pytest-xdist = "^3.3.1"
pytest-bdd = "^6.1.1"

[tool.pytest.ini_options]
markers = [
    "integration: tags a test as integration tests",
]



